CREATE TABLE REPORTS 
(
	REPORT_ID NUMBER NOT NULL ENABLE
	, NAME VARCHAR2(100) NOT NULL ENABLE
	, DESCRIPTION VARCHAR2(500)
	, REPORT_DESIGN BLOB
--	, FILENAME VARCHAR2(128 BYTE)
--	, SUBREPORT NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE
);