
delete from segment_experts;
delete from segment;
INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT), 0,17,'Metabolic Bone','Metabolic Bone',SYSDATE,'false');

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT), 0,17,'GHE/HOPE','GHE/HOPE',SYSDATE,'false');

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT), 0,17,'Nephrology','Nephrology',SYSDATE,'false');

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT), 0,17,'Oncology','Oncology',SYSDATE,'false');

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT), 0,17,'Inflammation','Inflammation',SYSDATE,'false');

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT), 0,17,'Heart Failure','Heart Failure',SYSDATE,'false');

COMMIT;

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL,TA,FA,REGION) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT),(SELECT SEGMENT_ID  FROM SEGMENT WHERE NAME LIKE 'Metabolic Bone'),17,'Medical Affairs','Medical Affairs',SYSDATE,'true', (SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Metabolic Bone' and option_id = (select id from option_names where name like 'Therapeutic Area')),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Medical Affairs'),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'USA'));

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL,TA,FA,REGION) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT),(SELECT SEGMENT_ID FROM SEGMENT WHERE NAME LIKE 'GHE/HOPE'),17,'Medical Affairs','Medical Affairs',SYSDATE,'true', (SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'GHE/HOPE' and option_id = (select id from option_names where name like 'Therapeutic Area')),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Medical Affairs'),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'USA'));

INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL,TA,FA,REGION) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT),(SELECT SEGMENT_ID FROM SEGMENT WHERE NAME LIKE 'Nephrology'),17,'Medical Affairs','Medical Affairs',SYSDATE,'true', (SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Nephrology' and option_id = (select id from option_names where name like 'Therapeutic Area')),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Medical Affairs'),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'USA'));


INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL,TA,FA,REGION) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT),(SELECT SEGMENT_ID FROM SEGMENT WHERE NAME LIKE 'Oncology'),17,'Medical Affairs','Medical Affairs',SYSDATE,'true', (SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Oncology' and option_id = (select id from option_names where name like 'Therapeutic Area')),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Medical Affairs'),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'USA'));


INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL,TA,FA,REGION) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT),(SELECT SEGMENT_ID FROM SEGMENT WHERE NAME LIKE 'Inflammation'),17,'Medical Affairs','Medical Affairs',SYSDATE,'true', (SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Inflammation' and option_id = (select id from option_names where name like 'Therapeutic Area')),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Medical Affairs'),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'USA'));


INSERT INTO SEGMENT (SEGMENT_ID,PARENT_ID,CREATED_BY,NAME,DESCRIPTION,CREATE_DATE,STRATEGY_LEVEL,TA,FA,REGION) VALUES 
((SELECT NVL(MAX(SEGMENT_ID),0)+1 FROM SEGMENT),(SELECT SEGMENT_ID FROM SEGMENT WHERE NAME LIKE 'Heart Failure'),17,'Medical Affairs','Medical Affairs',SYSDATE,'true', (SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Heart Failure' and option_id = (select id from option_names where name like 'Therapeutic Area')),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'Medical Affairs'),(SELECT ID FROM OPTION_LOOKUP WHERE OPTVALUE LIKE 'USA'));

COMMIT;